apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-postgres
  template:
    metadata:
      labels:
        app: tasks-postgres
    spec:
      containers:
        - name: tasks-postgres
          image: postgres
          ports:
            - containerPort: 8080
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: pg-root-username
                  name: postgres-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pg-root-password
                  name: postgres-secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: pg-db
                  name: postgres-secret
#            - name: POSTGRES_DB_NAME
#              valueFrom:
#                secretKeyRef:
#                  key: pg-db
#                  name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec: #actual configuration the way the service behaves
  type: ClusterIP
  ports: #ports that the clusterIP will expose or be available on
    - name: tasks
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: tasks-postgres