apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  pg-root-username: ZGFyZQ==
  pg-root-password: cGFzc3dvcmQ=
  pg-root-db: dGVzdHM=
  pg-db: dGFza21hbmFnZW1lbnQ=
  pgadmin-password: U3VwZXJTZWNyZXQ=
  pgadmin-email: ZGFyZS5mYWxvbGE3QGdtYWlsLmNvbQ==
